# This workflow will check if a new deb should be published

name: Check QMK Debian Package

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  deploy:
    runs-on: ubuntu-20.04
    container: debian:buster

    steps:
    - uses: actions/checkout@v2.3.4

    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y python3-pip
        python3 -m pip install requests

    - name: Check for update and trigger build
      run: ./check_version
      env:
        WORKFLOW_ID: debian-buster-publish.yml
