# This workflow will upload a .deb Package 

name: Upload QMK Ubuntu Package

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2.3.4

    # Environment Setup
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install dpkg-sig python3-pip python3-venv

    - name: Install python dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel 
        python3 -m pip install -r requirements-dev.txt

    - name: Install GPG secret key
      run: |
        echo -e "${{ secrets.QMK_GPG_SECRET_KEY }}" | gpg --batch --import
        gpg --list-secret-keys --keyid-format LONG

    # Build Ubuntu package
    - name: Build debian package
      run: ./build_deb_package.sh

    - name: Build debian package repository
      run: ./build_deb_repo.sh

    - name: Upload Debian Repo
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete
      env:
        AWS_S3_BUCKET: qmk-debian
        AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_KEY }}
        AWS_S3_ENDPOINT: https://nyc3.digitaloceanspaces.com
        SOURCE_DIR: 'deb_repo'
        DEST_DIR: 'dists/focal'
